package presentacion.GUI;

/**
 * Panel que representa la pantalla que aparece al iniciar sesión en la
 * aplicacion.
 *
 * @author Alici
 */
public class PanelBienvenida extends javax.swing.JPanel {

    /**
     * Constructor que inicializa los componentes del panel
     */
    public PanelBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondoMorado = new javax.swing.JPanel();
        pnlFondoBlanco = new javax.swing.JPanel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();

        pnlFondoMorado.setBackground(new java.awt.Color(221, 212, 240));
        pnlFondoMorado.setMinimumSize(new java.awt.Dimension(800, 500));
        pnlFondoMorado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreUsuario.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblNombreUsuario.setText("<nombre usuario>");
        pnlFondoBlanco.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 400, 156));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Logo.png"))); // NOI18N
        pnlFondoBlanco.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 190, -1));

        lblBienvenida.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblBienvenida.setText("Bienvenid@ ");
        pnlFondoBlanco.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 62, -1, 156));

        pnlFondoMorado.add(pnlFondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 790, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoMorado, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoMorado, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JPanel pnlFondoBlanco;
    private javax.swing.JPanel pnlFondoMorado;
    // End of variables declaration//GEN-END:variables
}
