/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallasReportes;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dto.ReporteResumenCubiculoDTO;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import presentacion.control.CoordinadorAplicacion;
import presentacion.control.CoordinadorNegocio;

/**
 *
 * @author erika
 */
public class frmrReporteEstadistico extends javax.swing.JFrame {
    /**
     * Coordinador para la logica de negocio de la aplicacion
     */
    private final CoordinadorNegocio controlNegocio = CoordinadorNegocio.getInstance();
    /**
     * Coordinador del flujo de pantallas de la aplicación.
     */
    private final CoordinadorAplicacion flujoPantallas = CoordinadorAplicacion.getInstance();
    private JFrame frmPadre;
    
    /**
     * Constructor que inicializa los componentes de la clase.
     */
    public frmrReporteEstadistico(JFrame frmPadre) {
        this.frmPadre = frmPadre;
        initComponents();
        setLocationRelativeTo(null);
        configurarTabla();
        cargarReporteEnTabla();
    }
    
    private void configurarTabla() {
        String[] columnas = {"Cubículo", "Total Citas", "Horas Usadas", "Ingresos"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable4.setModel(modelo);
    }
    private void cargarReporteEnTabla() {
        try {

            List<ReporteResumenCubiculoDTO> resumen = controlNegocio.generaReporteResumenCubiculo();
            DefaultTableModel modelo = (DefaultTableModel) jTable4.getModel();

            for (ReporteResumenCubiculoDTO dto : resumen) {
                modelo.addRow(new Object[]{
                    dto.getNombreCubiculo(),
                    dto.getTotalCitas(),
                    dto.getTotalCitas() + " h", 
                    String.format("$%,.2f", dto.getTotalIngresos())
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar el reporte: " + e.getMessage());
        }
    }
    private void exportarTablaAPDF() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setSelectedFile(new File("reporte_cubiculos.pdf"));
        int option = fileChooser.showSaveDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            try {
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream(file));
                document.open();

                // Título
                Font tituloFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);
                Paragraph titulo = new Paragraph("Reporte estadístico resumido", tituloFont);
                titulo.setAlignment(Element.ALIGN_CENTER);
                document.add(titulo);
                document.add(new Paragraph(" ")); // Espacio

                // Tabla
                PdfPTable pdfTable = new PdfPTable(jTable4.getColumnCount());
                for (int i = 0; i < jTable4.getColumnCount(); i++) {
                    pdfTable.addCell(jTable4.getColumnName(i));
                }

                for (int rows = 0; rows < jTable4.getRowCount(); rows++) {
                    for (int cols = 0; cols < jTable4.getColumnCount(); cols++) {
                        Object value = jTable4.getValueAt(rows, cols);
                        pdfTable.addCell(value != null ? value.toString() : "");
                    }
                }

                document.add(pdfTable);
                document.close();

                JOptionPane.showMessageDialog(this, "PDF generado con éxito.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al generar PDF: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        btnRegresar10 = new javax.swing.JButton();
        btnExportarPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(221, 212, 240));
        jPanel4.setPreferredSize(new java.awt.Dimension(1100, 680));

        lblTitulo3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblTitulo3.setText("Reporte uso de Cubiculo");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        btnRegresar10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-back-30.png"))); // NOI18N
        btnRegresar10.setBorderPainted(false);
        btnRegresar10.setContentAreaFilled(false);
        btnRegresar10.setFocusable(false);
        btnRegresar10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresar10MouseClicked(evt);
            }
        });
        btnRegresar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar10ActionPerformed(evt);
            }
        });

        btnExportarPDF.setBackground(new java.awt.Color(0, 0, 0));
        btnExportarPDF.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnExportarPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnExportarPDF.setText("Exportar a PDF");
        btnExportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar10)
                .addGap(42, 42, 42)
                .addComponent(lblTitulo3)
                .addGap(241, 241, 241))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExportarPDF)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 122, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo3)
                    .addComponent(btnRegresar10))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExportarPDF)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresar10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar10MouseClicked
       
    }//GEN-LAST:event_btnRegresar10MouseClicked

    private void btnRegresar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar10ActionPerformed
       flujoPantallas.regresarAlMenuPrincipal(this);
    }//GEN-LAST:event_btnRegresar10ActionPerformed

    private void btnExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPDFActionPerformed
        exportarTablaAPDF();
    }//GEN-LAST:event_btnExportarPDFActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarPDF;
    private javax.swing.JButton btnRegresar10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lblTitulo3;
    // End of variables declaration//GEN-END:variables
}
